version: "3.8"

services:
  # Frontend - Aplicación React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:5000/api

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PORT=5000
      - DB_TYPE=postgres
      # Variables para PostgreSQL en IBM Cloud
      - POSTGRES_HOST=90dd972f-f6bd-4155-8779-3bcaf3a01180.bkvfv1ld0bj2bdbncbeg.databases.appdomain.cloud
      - POSTGRES_PORT=32461
      - POSTGRES_DB=ibmclouddb
      - POSTGRES_USER=ibm_cloud_bdfa3f63_d92d_47f3_8002_13966ffb755e
      - POSTGRES_PASSWORD=5RMpLrl21XdCKo7PeXNhYwXDZQ4UF3iR
      - POSTGRES_SSL=true
      - POSTGRES_SSLMODE=verify-full
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-logs:/app/logs

# Volumes para persistencia de datos
volumes:
  backend-logs:
